### ISSUE TITLE
Issues with allocatable/pointer debug metadata

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/flang#413]
Debug metadata is not generated for allocatable/pointer variables. I think this happens because the variables that are used for printing the debug metadata are either the array descriptor or the assumed bound variables (z_b_*). 

program b1
  implicit none
  real, allocatable :: b(:)
  allocate(b(10))
  b=1
  print *,b
end program

**Comment by gklimowicz** [comment]
This issue should have been resolved in Flang PR#636 December 2012. @kiranchandramohan let me know if there are still issues with this.

**Comment by spellacl** [comment]
Issues still presenting with pointers in fortran debug metadata. Reproducer attached. Incorrect data appearing in locals of gdb when queried. Breakpoint set at line 27.

Pointer data has wrong bounds. For example,
storage1 = (-2, -1, -1, -1, -1, -1, -1, -1, -1, -3)
pointer1 = (-2, -1, -1, -1, -1, -1)
pointer1$sd = (35, 1, 25, 4, 536936448, 6, 6, 2, 0, 281473875404128, 1, 6, 1, 0, 1, 6)
z_b_4 = 1
z_b_7 = 1

Instead of:
pointer1 = (-1, -1, -1, -1, -1, -1)
storage1 = (-2, -1, -1, -1, -1, -1, -1, -1, -1, -3)

[reproducer.tar.gz](https://github.com/flang-compiler/flang/files/4629608/reproducer.tar.gz)

**Comment by louisespellacy** [comment]
Issues still presenting with pointers in fortran debug metadata. Reproducer attached. Incorrect data appearing in locals of gdb when queried. Breakpoint set at line 27.

Pointer data has wrong bounds. For example,
storage1 = (-2, -1, -1, -1, -1, -1, -1, -1, -1, -3)
pointer1 = (-2, -1, -1, -1, -1, -1)
pointer1$sd = (35, 1, 25, 4, 536936448, 6, 6, 2, 0, 281473875404128, 1, 6, 1, 0, 1, 6)
z_b_4 = 1
z_b_7 = 1

Instead of:
pointer1 = (-1, -1, -1, -1, -1, -1)
storage1 = (-2, -1, -1, -1, -1, -1, -1, -1, -1, -3)
[reproducer.tar.gz](https://github.com/flang-compiler/flang/files/4629719/reproducer.tar.gz)
